# Generated by Django 2.1.15 on 2020-11-29 20:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.SmallIntegerField(choices=[(1, '管理员'), (2, '普通员工')], default=3, verbose_name='用户类型')),
                ('is_show', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='是否可以修改数据')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='客户联系方式')),
                ('customer_info', models.TextField(null=True, verbose_name='客户信息')),
                ('create_date', models.DateField(null=True, verbose_name='客户创建日期')),
            ],
            options={
                'verbose_name_plural': '客户信息表',
            },
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_weight', models.CharField(max_length=50, null=True, verbose_name='整张材料重量')),
                ('slice_weight', models.CharField(max_length=50, null=True, verbose_name='单片成品重量')),
                ('individual_weight', models.CharField(max_length=50, null=True, verbose_name='单个成品重量')),
                ('leftovers_weight', models.CharField(max_length=50, null=True, verbose_name='边角料重量')),
                ('leftovers_percentage', models.CharField(max_length=50, null=True, verbose_name='边角料占比')),
                ('product_price', models.CharField(max_length=50, null=True, verbose_name='成品单价')),
                ('product_price_choices', models.SmallIntegerField(choices=[(1, '套'), (2, '公斤'), (3, '个')], default=1, null=True, verbose_name='成品单价的单位')),
                ('material_price', models.CharField(max_length=50, null=True, verbose_name='材料价格')),
                ('gross_profit', models.CharField(max_length=50, null=True, verbose_name='毛利润')),
                ('finished_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='成品数据填写人')),
            ],
            options={
                'verbose_name_plural': '成品数据信息',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50, null=True, verbose_name='材料名称')),
                ('show_type', models.SmallIntegerField(default=1, null=True, verbose_name='显示区分')),
                ('is_enable', models.SmallIntegerField(default=1, null=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name_plural': '材料信息表',
            },
        ),
        migrations.CreateModel(
            name='OneFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_height', models.CharField(max_length=10, null=True, verbose_name='材料宽')),
                ('material_thickness', models.CharField(max_length=10, null=True, verbose_name='材料厚度')),
                ('power_time', models.CharField(max_length=10, null=True, verbose_name='开机做片时间')),
                ('pulling_long', models.CharField(max_length=10, null=True, verbose_name='拉片长度')),
                ('shipment_num', models.CharField(max_length=50, null=True, verbose_name='每片出货个数')),
                ('slice_company', models.SmallIntegerField(choices=[(1, '个'), (2, '套')], default=1, verbose_name='出货单位')),
                ('ton_num', models.CharField(max_length=50, null=True, verbose_name='每吨出货片数')),
                ('ton_nums', models.CharField(max_length=50, null=True, verbose_name='每吨成品数量')),
                ('ton_slice_time', models.CharField(max_length=10, null=True, verbose_name='每吨拉片时长')),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Material', verbose_name='材料类别')),
                ('one_floor_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='一楼数据填写人')),
            ],
            options={
                'verbose_name_plural': '一楼产品信息表',
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_name', models.CharField(max_length=50, null=True, verbose_name='材料名称')),
                ('show_type', models.SmallIntegerField(default=1, null=True, verbose_name='显示区分')),
                ('is_enable', models.SmallIntegerField(default=1, null=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name_plural': '包装信息表',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True, verbose_name='品名')),
                ('product_status', models.SmallIntegerField(choices=[(1, '未开始'), (2, '制作中'), (3, '已完成')], default=1, verbose_name='产品状态')),
                ('product_img', models.ImageField(null=True, upload_to='product', verbose_name='产品图片')),
                ('p_create_date', models.DateField(null=True, verbose_name='产品创建时间')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Customer', verbose_name='客户')),
                ('finished_product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.FinishedProduct', verbose_name='成品数据')),
                ('one_floor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.OneFloor', verbose_name='对应一楼的流程')),
            ],
            options={
                'verbose_name_plural': '产品信息表',
            },
        ),
        migrations.CreateModel(
            name='ThreeFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_price', models.CharField(max_length=50, null=True, verbose_name='拆边工价')),
                ('three_packing_num_one', models.CharField(max_length=50, null=True, verbose_name='包装数量-个')),
                ('three_packing_num_two', models.CharField(max_length=50, null=True, verbose_name='包装数量-叠')),
                ('three_packing_num_three', models.CharField(max_length=50, null=True, verbose_name='包装数量-条')),
                ('three_packing_num_four', models.CharField(max_length=50, null=True, verbose_name='包装数量-层')),
                ('three_packing_nums', models.CharField(max_length=50, null=True, verbose_name='包装总数')),
                ('three_packing_price', models.CharField(max_length=50, null=True, verbose_name='三楼包装工价')),
                ('three_floor_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='三楼数据填写人')),
                ('three_packing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Packing', verbose_name='包装类型')),
            ],
            options={
                'verbose_name_plural': '三楼产品信息表',
            },
        ),
        migrations.CreateModel(
            name='TowFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knife_num', models.CharField(max_length=50, null=True, verbose_name='冲刀拼数')),
                ('bed_num', models.CharField(max_length=50, null=True, verbose_name='冲床张数')),
                ('bed_yield', models.CharField(max_length=50, null=True, verbose_name='冲床产量')),
                ('bed_yield_comany', models.SmallIntegerField(choices=[(1, '个'), (2, '套')], default=1, verbose_name='冲床产量单位')),
                ('bed_price', models.CharField(max_length=50, null=True, verbose_name='冲床工价')),
                ('two_packing_num_one', models.CharField(max_length=50, null=True, verbose_name='包装数量-个')),
                ('two_packing_num_two', models.CharField(max_length=50, null=True, verbose_name='包装数量-叠')),
                ('two_packing_num_three', models.CharField(max_length=50, null=True, verbose_name='包装数量-条')),
                ('two_packing_num_four', models.CharField(max_length=50, null=True, verbose_name='包装数量-层')),
                ('two_packing_nums', models.CharField(max_length=50, null=True, verbose_name='包装总数')),
                ('packing_num_choices', models.SmallIntegerField(choices=[(1, '个数'), (2, '重量')], default=1, verbose_name='包装数量类型（个数/重量）')),
                ('packing_weight', models.CharField(max_length=10, null=True, verbose_name='重量/公斤')),
                ('two_packing_price', models.CharField(max_length=50, null=True, verbose_name='二楼包装工价')),
                ('two_floor_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='二楼数据填写人')),
                ('two_packing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Packing', verbose_name='包装类型')),
            ],
            options={
                'verbose_name_plural': '二楼产品信息表',
            },
        ),
        migrations.AddField(
            model_name='productinfo',
            name='three_floor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ThreeFloor', verbose_name='对应三楼的流程'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='two_floor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TowFloor', verbose_name='对应二楼的流程'),
        ),
    ]
