# Generated by Django 2.1.15 on 2021-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211124_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedproduct',
            name='gross_profit',
            field=models.CharField(max_length=50, null=True, verbose_name='毛利润'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='individual_weight',
            field=models.CharField(max_length=50, null=True, verbose_name='单个成品重量'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='leftovers_percentage',
            field=models.CharField(max_length=50, null=True, verbose_name='边角料占比'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='leftovers_weight',
            field=models.CharField(max_length=50, null=True, verbose_name='边角料重量'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='material_price',
            field=models.CharField(max_length=50, null=True, verbose_name='材料价格'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='product_price',
            field=models.CharField(max_length=50, null=True, verbose_name='成品单价'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='sheet_weight',
            field=models.CharField(max_length=50, null=True, verbose_name='整张材料重量'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='slice_weight',
            field=models.CharField(max_length=50, null=True, verbose_name='单片成品重量'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='material_height',
            field=models.CharField(max_length=10, null=True, verbose_name='材料宽'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='material_thickness',
            field=models.CharField(max_length=10, null=True, verbose_name='材料厚度'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='power_time',
            field=models.CharField(max_length=10, null=True, verbose_name='开机做片时间'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='pulling_long',
            field=models.CharField(max_length=10, null=True, verbose_name='拉片长度'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='shipment_num',
            field=models.CharField(max_length=50, null=True, verbose_name='每片出货个数'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='ton_num',
            field=models.CharField(max_length=50, null=True, verbose_name='每吨出货片数'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='ton_nums',
            field=models.CharField(max_length=50, null=True, verbose_name='每吨成品数量'),
        ),
        migrations.AlterField(
            model_name='onefloor',
            name='ton_slice_time',
            field=models.CharField(max_length=10, null=True, verbose_name='每吨拉片时长'),
        ),
        migrations.AlterField(
            model_name='threefloor',
            name='edge_price',
            field=models.CharField(max_length=50, null=True, verbose_name='拆边工价'),
        ),
        migrations.AlterField(
            model_name='threefloor',
            name='three_packing_num_four',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-层'),
        ),
        migrations.AlterField(
            model_name='threefloor',
            name='three_packing_num_one',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-个'),
        ),
        migrations.AlterField(
            model_name='threefloor',
            name='three_packing_num_three',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-条'),
        ),
        migrations.AlterField(
            model_name='threefloor',
            name='three_packing_num_two',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-叠'),
        ),
        migrations.AlterField(
            model_name='threefloor',
            name='three_packing_nums',
            field=models.CharField(max_length=50, null=True, verbose_name='包装总数'),
        ),
        migrations.AlterField(
            model_name='threefloor',
            name='three_packing_price',
            field=models.CharField(max_length=50, null=True, verbose_name='三楼包装工价'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='bed_num',
            field=models.CharField(max_length=50, null=True, verbose_name='冲床张数'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='bed_price',
            field=models.CharField(max_length=50, null=True, verbose_name='冲床工价'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='bed_yield',
            field=models.CharField(max_length=50, null=True, verbose_name='冲床产量'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='knife_num',
            field=models.CharField(max_length=50, null=True, verbose_name='冲刀拼数'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='two_packing_num_four',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-层'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='two_packing_num_one',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-个'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='two_packing_num_three',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-条'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='two_packing_num_two',
            field=models.CharField(max_length=50, null=True, verbose_name='包装数量-叠'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='two_packing_nums',
            field=models.CharField(max_length=50, null=True, verbose_name='包装总数'),
        ),
        migrations.AlterField(
            model_name='towfloor',
            name='two_packing_price',
            field=models.CharField(max_length=50, null=True, verbose_name='二楼包装工价'),
        ),
    ]
